### ISSUE TITLE
How to generate names using English alphabet?

### ISSUE THREAD

**Issue by Lorenzo0111** [ItzSomebody/radon#102]
Is there a way to rename class fields and methods with normal characters and not things like the one in the image?

![image](https://user-images.githubusercontent.com/69311874/147849311-ad89d9a4-5fc8-46d1-abef-0d7d301de56f.png)

**Comment by ItzSomebody** [comment]
I have no idea what you meant by "normal characters", so I'll assume you are asking how you can generate names via letters from the English alphabet as a character set.

You can achieve that by listing the entirety of the English alphabet in both uppercase and lowercase as the dictionary key in the config. i.e.
```yml
dictionary: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
```

**Comment by Lorenzo0111** [comment]
Already did, but it is still using those characters

**Comment by ItzSomebody** [comment]
Other than possible encoding issues of your config file, I am not sure I can even come up with any scenarios as to that happening (default dictionary is set to the "alphanumeric" one if I remember correctly).

Can you upload your config file?

**Comment by Lorenzo0111** [comment]
https://pastebin.com/QqW4Pj92

**Comment by ItzSomebody** [comment]
Oh, you're using invokedynamics. I missed that from your screenshot. Due to the way that transformer works, the decompiled result is forced to look like that -- no way of getting around it.

If you're curious, https://github.com/ItzSomebody/radon/blob/master/src/main/java/me/itzsomebody/radon/transformers/obfuscators/references/FastInvokedynamicTransformer.java#L89 is how it works under the hood.

**Comment by Lorenzo0111** [comment]
Ok, thanks
