### ISSUE TITLE
Some feature is very weak

### ISSUE THREAD

**Issue by libYo** [ItzSomebody/Radon#15]
**Which version of Radon are you using? (Do not say "latest", if you do, your issue will be immediately closed)**
v0.8.2

I use today and decompile obfuscate jar with jadx but its so weak some feature like hide code, number obfuscation, crasher jadx easily deobfuscate,
You can make it even more secure.

**Comment by libYo** [comment]
I use it in Android, but invokedynamic requires java.lang.invoke.* , which is available only in the Android API 26.

https://developer.android.com/reference/java/lang/invoke/package-summary

**Comment by OpticFusion1** [comment]
@ItzSomebody I mean, i guess you could just make either stronger versions but seperate options, or just make stronger versions which only work with android applications

**Comment by ItzSomebody** [comment]
For the hide code, there is little I can actually do to make it stronger due to its nature. 

I’ve actually been experimenting with strengthening the number obf after seeing a smoke sample on java-deobfuscator’s issue tracker. 

As for the crasher, I may end up rewriting it altogether to prevent incompatibilities similar to the one @ByteCode-Dan.
