### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mimic2300** [ItzSomebody/Radon#38]
Hi,
I'm trying to use Radon in version 1.0.1 and I'm interested in these things. I will use it mainly for classic jar files (standalone) in Java SE 10 and later on 11

1) Is it possible to only obfuscate a specific package? E.g. only my package "my.app.nextname"

2) Would you be able to add a checkbox to skip a comment in the JAR archive? When I send someone an obfuscate application and he sees what he was obfuscated, it would only reduce security

3) Can you add descriptions for different methods/inputs in the GUI? E.g. what is it doing and preview the code before and after?

Thx

**Comment by ItzSomebody** [comment]
1. Regex allows for pattern exclusion so I believe so.

2. I'm not sure. There's multiple watermarks embedded by Radon so the comment is not the only watermark.

3. This will not be implemented. Sorry :(

**Comment by mimic2300** [comment]
Thanks for the reply. I have one more question.

I tried to obfuscate some JAR and open it in JD GUI 1.4 (java decompiler) and the result is the same as in the original JAR. I do not know if this is a bug or a JD application that does it so well that it returns to its original form.

**Comment by ItzSomebody** [comment]
JD-GUI is by definition: a piece of trash for deobfuscation. I don't think you decompiled an obfuscated class or you had it obfuscated very lightly. (Possibly a big bug I missed, but I doubt it.)

**Comment by jatins** [comment]
Adding here instead of a separate issue:
**Does is obfuscate JARs inside a jar?**

@ItzSomebody

**Comment by jatins** [comment]
Hey! After having had an extremely hard time with ProGuard, I came to this. It'd be great if you could answer couple questions:

**1. Does it obfuscate JARs inside a jar?**

**2. Is it possible to do only flow obfuscation and no name obfuscation?**
This is so that reflection calls work.

**3. Any performance impact of flow obfuscation?**

**4. How are the stack traces impacted?**
Followup: If I only do flow obfuscation, what is the impact on stacktraces then?

cc: @ItzSomebody

**Comment by ItzSomebody** [comment]
1. Nope.

2. Yes.

3. There will probably be a little bit of overhead, but that should speed up as the JIT inlines the methods.

4. Call stack shouldn't be affected.
